name: ToldLife

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  deploy:
    uses: MJbae/duvridge/.github/workflows/toldlife.yml@main
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
